CREATE TABLE "books" (
  "book_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "lang" varchar(50),
  "publisher_year" int,
  "location" varchar(255),
  "quantity" int,
  "author_name" varchar(255),
  "genre" varchar(100)
);

CREATE TABLE "borrowrecords" (
  "record_id" int PRIMARY KEY,
  "reader_id" int,
  "book_id" int,
  "borrow_date" date,
  "due_date" date,
  "return_date" date
);

CREATE TABLE "reader" (
  "reader_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" varchar(50) UNIQUE,
  "full_name" varchar(255),
  "email" varchar(255) UNIQUE,
  "phone_number" varchar(15) UNIQUE,
  "faculty" varchar(100),
  "status" varchar(50) DEFAULT 'Active'
);

CREATE TABLE "readeraccounts" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" varchar(50),
  "username" varchar(50) UNIQUE,
  "password" varchar(255),
  "status" varchar(50) DEFAULT 'Active',
  "last_login" timestamp
);

CREATE TABLE "readeractivitylog" (
  "activity_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int,
  "activity_description" text,
  "activity_date" timestamp
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int,
  "reader_id" int,
  "rating" int,
  "comment" text,
  "review_date" timestamp
);

COMMENT ON COLUMN "reviews"."rating" IS 'Từ 1 đến 5';

ALTER TABLE "borrowrecords" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("book_id");

ALTER TABLE "readeraccounts" ADD FOREIGN KEY ("student_id") REFERENCES "reader" ("student_id");

ALTER TABLE "readeractivitylog" ADD FOREIGN KEY ("account_id") REFERENCES "readeraccounts" ("account_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("book_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("reader_id") REFERENCES "reader" ("reader_id"); 

-- Thay đổi mã sinh viên trong bảng reader thì bảng readeraccounts cũng phải thay đổi theo (vì có khóa ngoại student_id)
  -- ALTER TABLE readeraccounts
  --   DROP CONSTRAINT IF EXISTS fk_student_id;

  -- ALTER TABLE readeraccounts
  --   ADD CONSTRAINT fk_student_id FOREIGN KEY (student_id)
  --   REFERENCES reader(student_id)
  --   ON UPDATE CASCADE
  --   ON DELETE RESTRICT;

