CREATE TABLE "books" (
  "book_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(255),
  "lang" VARCHAR(50),
  "publisher_year" INT,
  "location" VARCHAR(255),
  "quantity" INT,
  "author_name" VARCHAR(255),
  "genre" VARCHAR(100),
  "is_deleted" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "borrowrecords" (
  "record_id" int PRIMARY KEY,
  "reader_id" int,
  "book_id" int,
  "borrow_date" date,
  "due_date" date,
  "return_date" date
);

CREATE TABLE "reader" (
  "reader_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" varchar(50) UNIQUE,
  "full_name" varchar(255),
  "email" varchar(255) UNIQUE,
  "phone_number" varchar(15) UNIQUE,
  "faculty" varchar(100),
  "status" varchar(50) DEFAULT 'Active'
);

CREATE TABLE "readeraccounts" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" varchar(50),
  "username" varchar(50) UNIQUE,
  "password" varchar(255),
  "status" varchar(50) DEFAULT 'Active',
  "last_login" timestamp,
  "role" VARCHAR(20) DEFAULT 'student'
);

CREATE TABLE "readeractivitylog" (
  "activity_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int,
  "activity_description" text,
  "activity_date" timestamp
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int,
  "reader_id" int,
  "rating" int,
  "comment" text,
  "review_date" timestamp
);

CREATE TABLE "chats" (
  "chat_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" INT NOT NULL,
  "admin_id" INT, -- nếu bạn có bảng quản lý admin riêng
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "is_active" BOOLEAN DEFAULT TRUE
);

CREATE TABLE "messages" (
  "message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" INT NOT NULL,
  "sender_type" VARCHAR(20) NOT NULL, -- 'admin' hoặc 'reader'
  "sender_id" INT NOT NULL, -- reader_id hoặc admin_id tùy sender_type
  "message_text" TEXT,
  "sent_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "is_read" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "chat_attachments" (
  "attachment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id" INT NOT NULL,
  "file_url" VARCHAR(500),
  "file_type" VARCHAR(50),
  "uploaded_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "reviews"."rating" IS 'Từ 1 đến 5';

ALTER TABLE "chats" ADD FOREIGN KEY ("reader_id") REFERENCES "reader" ("reader_id");

ALTER TABLE "messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("chat_id");

ALTER TABLE "chat_attachments" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("message_id");

ALTER TABLE "borrowrecords" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("book_id");

ALTER TABLE "readeraccounts" ADD FOREIGN KEY ("student_id") REFERENCES "reader" ("student_id");

ALTER TABLE "readeractivitylog" ADD FOREIGN KEY ("account_id") REFERENCES "readeraccounts" ("account_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("book_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("reader_id") REFERENCES "reader" ("reader_id"); 

-- Thay đổi mã sinh viên trong bảng reader thì bảng readeraccounts cũng phải thay đổi theo (vì có khóa ngoại student_id)
  -- ALTER TABLE readeraccounts
  --   DROP CONSTRAINT IF EXISTS fk_student_id;

  -- ALTER TABLE readeraccounts
  --   ADD CONSTRAINT fk_student_id FOREIGN KEY (student_id)
  --   REFERENCES reader(student_id)
  --   ON UPDATE CASCADE
  --   ON DELETE RESTRICT;

